dist: xenial

language: python
python:
  - "3.7.0"

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - "export PYTHONPATH=.:$PYTHONPATH"
  - "export FLASK_USE_RELOADER=False"
  - "python biolink/app.py >> log.txt 2>&1 &"
  - sleep 3

# command to run tests
script: 
  - behave tests/

#after_success:
#  coveralls
