sudo: false

language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - "export PYTHONPATH=.:$PYTHONPATH"
  - "python biolink/app.py"
  - sleep 3

# command to run tests
script: 
  - behave tests/

#after_success:
#  coveralls
